---
include:
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.101/terraform-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.101/git-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.101/gitlab-toolkit.yml"

get-latest-terraform:
  extends: .get-latest-terraform

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate-terraform
  variables:
    ENVIRONMENTS: examples/complete

bump-tag:
  extends: .bump_minor_tag
